version: "3.8"

services:
  tf:
    image: nvcr.io/nvidia/tensorflow:22.04-tf2-py3
    deploy:
       resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]  
    stdin_open: true
    tty: true  
    volumes:
      - ./:/tensorflow
    working_dir: /tensorflow
